---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: simpledjangoapp
        image: mohamedmamdouhiv/gp-django-app:v1.0
        ports:
        - containerPort: 8000
