---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  namespace: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-selector
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: simple_django_app
        image: mohamedmamdouhiv/gp-django-app:v1.0
        ports:
        - containerPort: 8000
